### ISSUE TITLE
[민수] 크루관련해서 질문있습니다.

### ISSUE THREAD

**Issue by oct-sky-out** [Runvengers/RunningMate#36]
크루 생성때는 기본적으로 이미지를 첨부 안하는것으로 프론트에서 로직이 구현되어있습니다.
하지만 정보 수정때 부터는 이미지 첨부가 가능하게 로직이 구성되어있는데요.

1. 크루에도 크루 대표 이미지가 필요하지 않을까요?
2. 또한 오픈채팅방 링크도 수정이 가능해야할 필요가 있다고 생각합니다. 

정보 변경은 위 2가지에 대한 기능추가를 해보시는건 어떠신가요?

**Comment by java-saeng** [comment]
1. 맞아요 그러면 crew에도 img URL을 첨부할 수 있도록 할게요

2. 정보 수정 로직 변경할게요
