### ISSUE TITLE
[크루] 크루 정보수정 API 수정요청

### ISSUE THREAD

**Issue by oct-sky-out** [Runvengers/RunningMate#40]
<img width="2042" alt="스크린샷 2022-01-23 18 13 40" src="https://user-images.githubusercontent.com/60546275/150671980-020f9bb7-5820-466c-b613-72857f9084ef.png">

![image](https://user-images.githubusercontent.com/60546275/150672030-5f96fbcc-63b3-4a62-bc95-6bf87137d75c.png)

업데이트 완료 - 크루 상세 정보에 위 예외가 발생했습니다.

## 궁금한점
혹시 정보수정, 크루 삭제, 크루원 추방 같은 기능에 토큰이 필요할까요?
정보수정에는 토큰없이 보내긴했는데요... 잘 되는거같아서 혹시 백단에서는 토큰이라는 보안장치가 필요할까 싶어서요

**Comment by java-saeng** [comment]
![image](https://user-images.githubusercontent.com/62413589/150672170-3281e7ce-3f48-4195-94f8-6aa6905dd799.png)
requestBody로 줘서 그런거 아닐까요??

일단 content-type에서 문제가 생긴 것 같습니다.

**Comment by oct-sky-out** [comment]
@java-saeng  확인했습니다 컨텐츠타입 다시보고 알려드리겠습니다.

**Comment by java-saeng** [comment]
혹시 정보수정, 크루 삭제, 크루원 추방 같은 기능에 토큰이 필요할까요?
정보수정에는 토큰없이 보내긴했는데요... 잘 되는거같아서 혹시 백단에서는 토큰이라는 보안장치가 필요할까 싶어서요

이 부분에 대해서는 정보 수정, 크루 삭제, 크루원 추방 경우는 권한이 모두 크루장에게 있어야하는데
크루장인지 아닌지 확인하기 위해 토큰이 필요하다고 생각했습니다.
그런데 저희 쪽이 토큰을 요청하지는 않습니다 !

**Comment by oct-sky-out** [comment]
> 혹시 정보수정, 크루 삭제, 크루원 추방 같은 기능에 토큰이 필요할까요? 정보수정에는 토큰없이 보내긴했는데요... 잘 되는거같아서 혹시 백단에서는 토큰이라는 보안장치가 필요할까 싶어서요
> 
> 이 부분에 대해서는 정보 수정, 크루 삭제, 크루원 추방 경우는 권한이 모두 크루장에게 있어야하는데 크루장인지 아닌지 확인하기 위해 토큰이 필요하다고 생각했습니다. 그런데 저희 쪽이 토큰을 요청하지는 않습니다 !

네 확인했습니다 저희쪽에서 최대한 해보고 협력이 필요한 구간은 따로 요청해보겠습니다!.
그리고 컨텐츠는 텍스트로 보냈는데 제 쪽에서 그냥 json처럼 보냈더군요 ㅋㅋ 지금은 잘 되네요!

**Comment by java-saeng** [comment]
넵 굳굳
크루장에게만 버튼이 보이는 게 잘 안되시면 말씀해주세요
