### ISSUE TITLE
[민수] 크루 관련 정보 API 추가필요.

### ISSUE THREAD

**Issue by oct-sky-out** [Runvengers/RunningMate#43]
안녕하세요 현우님 기환님 설날의 첫 연휴 시작날부터 질문드리네요. 😵‍💫

  1. 노션의 명세를 보시면 아시겠지만 크루에 들어가고싶은 신청자들의 목록을 크루장이 관리를 해야하는데 이를 받을 API가 존재하지않습니다. 
  2. 각 유저들이 하나의 크루에만 신청이 가능한데 유저가 어떤 크루에 가입 신청을 하였는지 프론트에서 구분할 방법이 없습니다.
    2-1 솔루션을 생각해 보았는데, 유저가 크루가입 신청을 한 이 후 유저 정보에 신청한 "크루 id"를 갱신하는 방법은 어떨까요?
  3. 자진탈토의 경우, 크루장이 자진탈퇴 시도 시 위임을 한 뒤 자진탈퇴가 가능하다고 말씀하셨죠?

**Comment by SeoKiHwan** [comment]
1. 크루 상세페이지를 조회하는 API를 호출하시면 CrewDto를 받게 되실텐데, 이 안에 해당 크루에 요청을 넣은 유저들의 닉네임이 존재합니다. 
   크루 신청 목록 API를 따로 만드는게 더 편하실까요??
2. 해당유저가 크루에 '가입되어 있을 때'는 크루 신청을 못하게 만들었습니다. 즉 크루에 속해 있기 전까지는 여러 크루에 가입신청을 넣을 수 있게됩니다.  이 부분을 "한 번에 한 크루에만 가입신청이 가능하게 만들어야 한다"로 바꿀지는 팀원분들과 회의를 해봐야겠네요 :)

3. 네 맞습니다. 다만 서버쪽에서 처리하지는 않고 "위임API"가 있습니다. 아마 크루장이 크루에서 자진 탈퇴하는 경우 이 API를 프론트쪽에서 호출하는 절차로 정했던 것 같습니다~

**Comment by java-saeng** [comment]
1. crewDto에 request목록과 crewLeaderId를 가지고 있습니다
민수님이 말씀하시는거는 이 사람이 "크루장인가" , "요청 목록을 보고싶다" 둘 중에 어떤 건지 모르겠습니다!

2. 기환님 말과 동일합니다

3. 넵 그래서 저희 쪽에서는 위임 api가 따로 있습니다.

**Comment by oct-sky-out** [comment]
> 1. 크루 상세페이지를 조회하는 API를 호출하시면 CrewDto를 받게 되실텐데, 이 안에 해당 크루에 요청을 넣은 유저들의 닉네임이 존재합니다.
>    크루 신청 목록 API를 따로 만드는게 더 편하실까요??
> 2. 해당유저가 크루에 '가입되어 있을 때'는 크루 신청을 못하게 만들었습니다. 즉 크루에 속해 있기 전까지는 여러 크루에 가입신청을 넣을 수 있게됩니다.  이 부분을 "한 번에 한 크루에만 가입신청이 가능하게 만들어야 한다"로 바꿀지는 팀원분들과 회의를 해봐야겠네요 :)
> 3. 네 맞습니다. 다만 서버쪽에서 처리하지는 않고 "위임API"가 있습니다. 아마 크루장이 크루에서 자진 탈퇴하는 경우 이 API를 프론트쪽에서 호출하는 절차로 정했던 것 같습니다~

1. 그럼 CrewDto들이 담긴 배열 안에는 이미 가입된 유저와 요청을 넣은 유저가 함께들어있는것인가요?
2. 네 백엔드에는 이미 가입되었을 때 못하게 블로킹 처리를 다하신것을 저번에 기능 시연하셨을때 본 것을 기억합니다. 하지만 프론트에서 사용자가 
    크루 가입 신청을 해놓은 상태인지에 대한 구분을 할 수 없는 이유때문에 로그인 시 userDto에 크루 요청상태에 대한 값을 전달 부탁받고자 말씀 
    드린 것입니다.
3. 알려주셔서 감사합니다.

**Comment by oct-sky-out** [comment]
> 1. crewDto에 request목록과 crewLeaderId를 가지고 있습니다
>    민수님이 말씀하시는거는 이 사람이 "크루장인가" , "요청 목록을 보고싶다" 둘 중에 어떤 건지 모르겠습니다!
> 2. 기환님 말과 동일합니다
> 3. 넵 그래서 저희 쪽에서는 위임 api가 따로 있습니다.

1. 크루장이 관리 크루 가입 요청자들을 관리해야하므로 "가입 요청목록을 보고싶다."는 부탁을 드리고싶습니다.
3. 네 위임은 저희가 처리하도록 하겠습니다.

**Comment by java-saeng** [comment]
1. crewDto에 requests라고 있습니다!
