### ISSUE TITLE
[유저 기능] 유저 기능의 로그인의 response와 관련한 질문있습니다.

### ISSUE THREAD

**Issue by oct-sky-out** [Runvengers/RunningMate#66]
![스크린샷 2022-02-07 시간: 01 17 55](https://user-images.githubusercontent.com/60546275/152690410-5bc85c41-f746-4ae4-a1d7-e28ba56f8ee6.png)

![image](https://user-images.githubusercontent.com/60546275/152690421-75754ff7-176e-4dbd-a6b5-e15ea5437bf1.png)
### [참고사진 - 유저 로그인 후 user data의 구성]
![image](https://user-images.githubusercontent.com/60546275/152690447-8f246329-5319-43e1-abeb-473262a2f167.png)

위와같은형식으로 유저가 로그인 후 크루이름을 안던져주는 현상이 발생하고 null값으로 그대로 유지가 됩니다. 한번 확인부탁드립니다.

**Comment by java-saeng** [comment]
저희 이슈에도 올려놨었는데 그때 기환님이 이게 버그가 아니라 로그인할 때는 굳이 크루의 정보가 필요없다고 생각이 들어서 이렇게 했습니다,, 혹시 필요하신가요??
