### ISSUE TITLE
[API 요청] 로그아웃 API 제작 부탁드립니다.

### ISSUE THREAD

**Issue by oct-sky-out** [Runvengers/RunningMate#9]

**Comment by SeoKiHwan** [comment]
jwt 인증방식에서 로그아웃이 쉬운 문제는 아닌거 같습니다.(추가 토큰 발행이 필요할 수도..)
좀 더 구상해보고 코멘트 남기겠습니다 :)

**Comment by oct-sky-out** [comment]
@SeoKiHwan 네 알겠습니다.
구상 완료되시면 연락주세요! 즐코하십시오!😉
